blog/urls.py
# 2번줄: admin임포트 삭제
from django.urls import path
from . import views
# 4번줄: 어떤 것에서든 views를 임포트한다.

app_name = 'blog'
urlpatterns = [
    path('postList/', views.postList, name='postList'), 
    path('<int:pk>/detail/', views.postDetail, name='postDetail'),
    path('postNew/', views.postNew, name='postNew'),
    path('<int:pk>/postEdit', views.postEdit, name='postEdit'),
    path('drafts/',views.post_draft_list,name='post_draft_list'),
    path('<int:pk>/publish', views.post_publish, name='post_publish'),
    path('<int:pk>/remove/', views.post_remove, name='post_remove'),

]

jango3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    
]


'''

	jango3/urls.py

	프로젝트 생성시 프로젝트폴더인 jango3 안에는 urls.py라는 파일이 있다.
	이 파일에 모든 urlpattern을 모아서 저장한다.

	이 프로젝트에 만든 앱이 많아지고(지금은 students앱 밖에 없지만)
	그 앱에 대한 view가 많아지면 urlpatterns에 들어가는 데이터는 굉장히 많아질 것이다.
	예를들어 students앱에 대한 뷰가 10개라고 할때 
	모든 10개의 뷰에 대한 urlpatterns을 여기에 저장하는 것보다는
	유지보수를 쉽게하기 위해.. 앱 각각의 담당 url로도 이동할 수 있도록하자.

	따라서 students앱폴더 내에 urls.py파일을 새로 하나더 만들도록하고
	여기 이 파일에서 그 urls.py로 이동할 수 있도록 하자.

'''

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    # /polls/
    path('', views.IndexView.as_view(), name='index'),
    # /polls/5
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

students/urls.py
# 2번줄: admin임포트 삭제
from django.urls import path
from . import views
# 4번줄: 어떤 것에서든 views를 임포트한다.

app_name = 'students'
urlpatterns = [
    path('reg/', views.regStudent, name='reg'),
    path('regCon/', views.regConStudent, name='regCon'),
    path('all/', views.readStudentAll, name='stuAll'),
    path('<str:name>/det/', views.detStudent, name='stuDet'),
    path('<str:name>/mod/', views.readStudentOne, name='stuMod'),
    path('modCon/', views.modConStudent , name='modCon'),
    path('<str:name>/del/', views.delStudent, name='stuDel'),

]

'''
	/students/reg에 들어오면
	views의 regStudent함수가 실행된다.
	이 urlpattern의 이름은 'reg'로 지정한다.
'''

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	# 다른 모델에 대한 링크
	author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
	s_name = models.CharField(max_length=100)
	s_major = models.CharField(max_length=100)
	s_age = models.IntegerField(default=0)
	s_grade = models.IntegerField(default=0)
	s_gender = models.CharField(max_length=30)

	def __str__(self):
		return self.s_name
		

blog/forms.py
from django import forms

from blog.models import Post

class PostForm(forms.ModelForm): # 장고에게 PostForm클래스는 ModelForm임을 알려준다.
	class Meta:
		model = Post # 폼을 만들기위해 어떤 model을 쓸건지 장고에게 알려주는 구문
		fields = ('title', 'text')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from blog.models import Post
from blog.forms import PostForm
from django.shortcuts import redirect


# Create your views here.
def postList(request):
	# 데이터베이스에 저장된 포스트 데이터를 가지고 온다.
	qs = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	# qs에 저장된 테이블 데이터는 student_list저장되고
	# 이는 context 딕셔너리에 실려서 readStudents.html템플릿에 전달된다.
	# 템플릿에서는 context를 통해 전달받은 데이터에 접근할 수 있다.
	context = {'posts': qs}
	return render(request, 'blog/postList.html', context)


def postDetail(request, pk):
	qs = get_object_or_404(Post, pk=pk)
	context = {'post': qs}
	return render(request, 'blog/postDetail.html', context)

def postNew(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			#post.published_date = timezone.now()
			post.save()

			return redirect('blog:postDetail', pk=post.pk)
	else:
		form = PostForm()

	context = {'form': form}
	return render(request, 'blog/postNew.html', context)

def postEdit(request, pk):
	qs = get_object_or_404(Post, pk=pk)

	if request.method == "POST":
		form = PostForm(request.POST, instance=qs)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			#post.published_date = timezone.now()
			post.save()

			return redirect('blog:postDetail', pk=post.pk)

	else:
		form = PostForm(instance=qs)
	
	context = {'form': form}
	return render(request, 'blog/postNew.html', context)


def post_draft_list(request):
	# ONLY unpublished posts from DB
	qs = Post.objects.filter(published_date__isnull=True).order_by('created_date')
	context = {'posts': qs}
	return render(request, 'blog/post_draft_list.html', context)


def post_publish(request, pk):
	qs = get_object_or_404(Post, pk=pk)
	qs.publish()
	return redirect('blog:postDetail', pk=pk)


def post_remove(request, pk):
	qs = get_object_or_404(Post, pk=pk)
	qs.delete()
	return redirect('blog:postList')

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""Return the last five published questions."""
		return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		context = {
			'question': question,
			'error_message': "you didn't select a choice.",
		}
		return render(request, 'polls/detail.html', context)

	else:

		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

students/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from students.models import Student

# Create your views here.
def regStudent(request):
	return render(request, 'students/registerStudent.html')


def regConStudent(request):
	name = request.POST['name']
	major = request.POST['major']
	age = request.POST['age']
	grade = request.POST['grade']
	gender = request.POST['gender']
	

	# 데이터베이스에 request로부터 전달받은 데이터를 테이블에 저장하는 쿼리
	qs = Student(s_name = name, s_major = major, s_age=age, s_grade=grade, s_gender = gender)
	qs.save()

	# 마지막으로 웹페이지사용자에게 "학생전체보기 페이지" url인 students/all 에 연결시켜준다.
	return HttpResponseRedirect(reverse('students:stuAll'))


def readStudentAll(request):
	# 데이터베이스에 저장된 모든데이터를 가져온다.
	qs = Student.objects.all()
	# qs에 저장된 테이블 데이터는 student_list저장되고
	# 이는 context 딕셔너리에 실려서 readStudents.html템플릿에 전달된다.
	# 템플릿에서는 context를 통해 전달받은 데이터에 접근할 수 있다.
	context = {'student_list': qs}
	return render(request, 'students/readStudents.html', context)


def detStudent(request, name):
	qs = Student.objects.get(s_name = name)
	context = {'student_info': qs}
	return render(request, 'students/detailStudent.html', context)


def readStudentOne(request, name):
	qs = Student.objects.get(s_name = name)
	context = {'student_info': qs}
	return render(request, 'students/modifyStudent.html', context)

def modConStudent(request):
	# modifyStudent.html로부터 수정된 학생데이터를 가져온다.
	name = request.POST['name']
	major = request.POST['major']
	age = request.POST['age']
	grade = request.POST['grade']
	gender = request.POST['gender']

	# 데이터베이스에서 특정 학생의 데이터를 가져온다.
	s_qs = Student.objects.get(s_name=name)

	# 데이터베이스의 값을 수정된값으로 바꾼다.
	s_qs.s_name = name
	s_qs.s_major = major
	s_qs.s_age = age
	s_qs.s_grade = grade
	s_qs.s_gender = gender

	s_qs.save()

	# 사용자의 페이지를 학생전체보기페이지로 리디랙트한다.
	return HttpResponseRedirect(reverse('students:stuAll'))

def delStudent(request, name):
	qs = Student.objects.get(s_name=name)
	qs.delete()

	return HttpResponseRedirect(reverse('students:stuAll'))

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" charset="utf-8">
	<title>postList.html</title>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Modak&display=swap" rel="stylesheet">
</head>
<body>
	<div class="page-header">
		{% if user.is_authenticated %}
			<a href="{% url 'blog:postNew' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
			<a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
		{% endif %}
		
		<h1><a href="{% url 'blog:postList' %}">PLASTIC BARCODE</a></h1>
	</div>

	<div class="content container">
		<div class="row">
			<div class="col-md-8">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>

</body>
</html>

blog/templates/blog/postDetail.html
{% extends 'blog/base.html' %}

{% block content %}



	<div class="post">
		{% if post.published_date %}
			<div class="date">
				{{ post.published_date }}
			</div>

		{% else %}
			<a href="{% url 'blog:post_publish' pk=post.pk %}" class="btn btn-default">PUBLISH</a>
		{% endif %}	

		{% if user.is_authenticated %}
			<a class="btn btn-default" href="{% url 'blog:postEdit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
		{% endif %}	

		<h1>{{ post.title }}</h1>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>
		



{% endblock %}

blog/templates/blog/postList.html
{% extends 'blog/base.html' %}

{% block content %}



	{% if posts %}

		{% for post in posts %}
		<div>
			<p>published: {{ post.published_data }}</p>
			<h2><a href="{% url 'blog:postDetail' pk=post.pk %}">{{ post.title }}</a></h2>
			<p>{{ post.text|linebreaksbr }}</p>
		</div>
		{% endfor %}

	{% else %}
		<p>posts : 0</p>
	{% endif %}	




{% endblock %}

blog/templates/blog/postNew.html
{% extends 'blog/base.html' %}

{% block content %}



	<h1>NEW POST</h1>
	<form method="POST" class="post-form">
		{% csrf_token %}

		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">SAVE</button>
	</form>



{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}



	{% for post in posts %}
	<div class="post">
		<p class="date">created: {{ post.create_date|date:'d-m-Y' }}</p>
		<h1><a href="{% url 'blog:postDetail' pk=post.pk %}">{{ post.title }}</a></h1>
		<p>{{ post.text|truncatechars:200 }}</p>
	</div>



	{% endfor %}




{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}

	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
	{% endfor %}
	<input type="submit" name="Vote">
	
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}

	<ul>

		{% for question in latest_question_list %}
			<li>
				<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
			</li>
		{% endfor %}
	</ul>


{% else %}
	<p>NO POLLS ARE AVAILABLE.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>

	{% for choice in question.choice_set.all %}
		<li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
	{% endfor %}

</ul>

<a href="{% url 'polls:detail' question.id %}">VOTE AGAIN?</a>

students/templates/students/detailStudent.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" charset="utf-8">
	<title>TITLE</title>
</head>
<body>
	<p>DETAIL OF THE STUDENT: {{student_info.s_name}}</p>

	{% if student_info %}
		name: {{student_info.s_name}} </br>
		major: {{student_info.s_major}} </br>
		age: {{student_info.s_age}} </br>
		grade: {{student_info.s_grade}} </br>
		gender: {{student_info.s_gender}} </br>	
	{% else %}
		<p>students : 0</p>
	{% endif %}	

	</br>

	<a href="{% url 'students:stuMod' student_info.s_name %}">MODIFY THIS STUDENT</a></br>
	<a href="{% url 'students:stuDel' student_info.s_name %}">DELETE THIS STUDENT</a></br></br>
	<a href="{% url 'students:stuAll' %}">SHOW ALL THE STUDENTS</a></br>
	<a href="{% url 'students:reg' %}">REGISTER NEW STUDENT</a></br>

</body>
</html>

students/templates/students/modifyStudent.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" charset="utf-8">
	<title>TITLE</title>
</head>
<body>
	<p>MODIFY STUDENT HERE</p>

	{% if student_info %}
		<form action="{% url 'students:modCon' %}" method="post">
			{% csrf_token %}
			name : {{student_info.s_name}}</br>
			<input type="hidden" name="name" value={{student_info.s_name}}></br> 
			
			major : <input type="text" name="major" value={{student_info.s_major}}></br> 
			age : <input type="text" name="age" value={{student_info.s_age}}></br> 
			grade : <input type="text" name="grade" value={{student_info.s_grade}}></br> 
			gender : <input type="text" name="gender" value={{student_info.s_gender}}></br> 
			<input type="submit" name="Modify"></br>

		</form>
	{% else %}
		<p>student: 0</p>
	{% endif %}
	
</body>
</html>

students/templates/students/readStudents.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" charset="utf-8">
	<title>TITLE</title>
</head>
<body>
	<p>READ ALL STUDENTS INFORMATION HERE</p>

	{% if student_list %}
	<ol>
		{% for s in student_list %}
		<li>
			<a href="{% url 'students:stuDet' s.s_name %}">{{s.s_name}}</a>
			<a href="{% url 'students:stuMod' s.s_name %}">MODIFY THIS DATA</a>
			<a href="{% url 'students:stuDel' s.s_name %}">DELETE THIS DATA</a>
		</li>
		{% endfor %}
	</ol>
	{% else %}
		<p>students : 0</p>
	{% endif %}	

	</br>
	<a href="{% url 'students:reg' %}">REGISTER NEW STUDENT</a>

</body>
</html>

students/templates/students/registerStudent.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" charset="utf-8">
	<title>TITLE</title>
</head>
<body>
	<p>REGISTER STUDENT HERE</p>

	<form action="{% url 'students:regCon' %}" method="post">
	{% csrf_token %}
		name: <input type="text" name="name"></br>
		major: <input type="text" name="major"></br>
		age: <input type="text" name="age"></br>
		grade: <input type="text" name="grade"></br>
		gender: <input type="text" name="gender"></br>
		<input type="submit" name="Register"></br>
	</form>
</body>
</html>